apiVersion: batch/v1
kind: Job
metadata:
  name: infraledger-migrate
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: infraledger-api-sa
      restartPolicy: Never
      containers:
        - name: migrate
          image: 564907679931.dkr.ecr.eu-west-1.amazonaws.com/infraledger-api:latest
          command: ["python", "-m", "flask", "--app", "wsgi", "db", "upgrade"]
          resources:
            requests:
              cpu: "100m"
              memory: "192Mi"
            limits:
              cpu: "500m"
              memory: "384Mi"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: infraledger-db-secret
                  key: DATABASE_URL
            - name: AWS_REGION
              value: "eu-west-1"
            - name: AWS_PRICING_API_REGION
              value: "us-east-1"