"""create price_cache table

Revision ID: fc217a37537b
Revises: 57ee2815f02e
Create Date: 2026-07-31 23:53:19.509645

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fc217a37537b"
down_revision = "57ee2815f02e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price_cache",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("service_code", sa.String(length=50), nullable=False),
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("region", sa.String(length=30), nullable=False),
        sa.Column("price_per_unit", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column(
            "fetched_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "service_code", "sku", "region", name="uq_price_cache_lookup"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("price_cache")
    # ### end Alembic commands ###
